### PR TITLE
Merge changes from dev for verson 1.0

### PR DESCRIPTION
**Pull request by HaydenElza**
We still have a couple of tasks before we can merge dev into master ([see here](https://github.com/WIStCart/plss-locator/projects/1)):

- [x] Add SCO header
- [x] Nearby as DTRSQQQ
- [x] Move CSS and JS to separate files
- [x] Move about info to header

### CODE REVIEW

**Comment by HaydenElza** [comment]
It looks like the application is ready for review. See here: https://dev.sco.wisc.edu/plss-locator/

Checks:

- [ ] Page load speed
- [ ] Toggle satellite
- [ ] Zoom/Pan
  - [ ] Min zoom: 8
  - [ ] Max zoom: 18
  - [ ] Pan: WI always in view
- [ ] Controls
  - [ ] Zoom in/out buttons
  - [ ] Geolocate Control
    - [ ] Outside extent
  - [ ] Search
- [ ] Click on map
  - [ ] Lat/Long displayed
  - [ ] PLSS info displayed
  - [ ] Verbal description
  - [ ] Nearby features
    - [ ] Loading indicator while searching
    - [ ] Empty when none nearby
    - [ ] Displays one or more depending on location
  - [ ] Closed side widget opens on click
- [ ] Header
  - [ ] About
- [ ] Mobile
  - [ ] Greater than 640px
  - [ ] Between 600px and 640px
    - [ ] Search control moves to bottom right
  - [ ] Less than 600px
    - [ ] Header gone
    - [ ] Menu button
      - [ ] About
    - [ ] Search control
    - [ ] Side widget open/close
    - [ ] Closed side widget opens on click

**Review by Wiscmapper — COMMENTED** [review]
"about" link in the header that displays the about info.

Not a fan of the big "get device location" button, esp. since the device location isn't very reliable.  I just clicked (connected to work PC via VPN) and it says in I'm western Iowa.
image

**Comment by HaydenElza** [comment]
@Wiscmapper 
I was debating whether or not to move the info button to the header. On one hand, it totally makes sense to match the style of the other applications that have an about link. On the other hand, that would make use of the modal functionally that I hope to change in the future. Perhaps I should just change it over to be consistent, albeit not the way I would like for it to be.

Regarding the "Get Device Location", I plan to change that to a leaflet control in the future. As far as reliability, that has to do with the network settings at Sci Hall. Not too long ago they were set somewhere in Madison, but after a recent network restart it now is just set as "United States". Try searching where am I in google; you'll get a similar result.

Thanks for the feedback!

**Comment by Wiscmapper** [comment]
I suggest you change the header to match the functionality used in other apps, and describe /document the new approach so we can update all apps together later on.  We have a lot of student labor this summer, so I think the modal update would be great task in June or July.

**Comment by HaydenElza** [comment]
Merged pull request #9 from @Wiscmapper which added the locator control and removed the _Get Device Location_ button. Moved about information to header rather than a button on map.

**Pull request merged**
